// Generated by gencpp from file obj_msgs/ObjectMsg.msg
// DO NOT EDIT!


#ifndef OBJ_MSGS_MESSAGE_OBJECTMSG_H
#define OBJ_MSGS_MESSAGE_OBJECTMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace obj_msgs
{
template <class ContainerAllocator>
struct ObjectMsg_
{
  typedef ObjectMsg_<ContainerAllocator> Type;

  ObjectMsg_()
    : x(0)
    , y(0)
    , height(0.0)
    , width(0.0)
    , distance(0.0)
    , class_name()  {
    }
  ObjectMsg_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , height(0.0)
    , width(0.0)
    , distance(0.0)
    , class_name(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef float _height_type;
  _height_type height;

   typedef float _width_type;
  _width_type width;

   typedef float _distance_type;
  _distance_type distance;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;





  typedef boost::shared_ptr< ::obj_msgs::ObjectMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obj_msgs::ObjectMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectMsg_

typedef ::obj_msgs::ObjectMsg_<std::allocator<void> > ObjectMsg;

typedef boost::shared_ptr< ::obj_msgs::ObjectMsg > ObjectMsgPtr;
typedef boost::shared_ptr< ::obj_msgs::ObjectMsg const> ObjectMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obj_msgs::ObjectMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obj_msgs::ObjectMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::obj_msgs::ObjectMsg_<ContainerAllocator1> & lhs, const ::obj_msgs::ObjectMsg_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.height == rhs.height &&
    lhs.width == rhs.width &&
    lhs.distance == rhs.distance &&
    lhs.class_name == rhs.class_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::obj_msgs::ObjectMsg_<ContainerAllocator1> & lhs, const ::obj_msgs::ObjectMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace obj_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::obj_msgs::ObjectMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obj_msgs::ObjectMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obj_msgs::ObjectMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obj_msgs::ObjectMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obj_msgs::ObjectMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obj_msgs::ObjectMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obj_msgs::ObjectMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56b107eaebcdaea230854f3edfee5b4f";
  }

  static const char* value(const ::obj_msgs::ObjectMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56b107eaebcdaea2ULL;
  static const uint64_t static_value2 = 0x30854f3edfee5b4fULL;
};

template<class ContainerAllocator>
struct DataType< ::obj_msgs::ObjectMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obj_msgs/ObjectMsg";
  }

  static const char* value(const ::obj_msgs::ObjectMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obj_msgs::ObjectMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
"float32 height\n"
"float32 width\n"
"float32 distance\n"
"string class_name\n"
;
  }

  static const char* value(const ::obj_msgs::ObjectMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obj_msgs::ObjectMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.distance);
      stream.next(m.class_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obj_msgs::ObjectMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obj_msgs::ObjectMsg_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJ_MSGS_MESSAGE_OBJECTMSG_H
